### ISSUE TITLE
Remove upper limit for Sphinx requirement

### ISSUE THREAD

**Issue by albireox** [bitprophet/releases#87]
Would it be possible to remove the requirement that Sphinx must be <1.8.0? As far as I have been able to test there is nothing broken with the current version of releases and the latest Sphinx 2.1+, and this is causing problems with version resolution in tools like poetry.

**Comment by bitprophet** [comment]
Looks like ReadTheDocs recently (well. like. march 2019?) started using Sphinx 1.8-ish so I think I need this myself now.

IIRC the pin in our own setup.py here was mostly defensive (Sphinx loves breaking pseudo-private APIs each minor release, though, I get it). A lot of my other related Sphinx tooling gets its claws deeper into Sphinx and cares more about its version, which may have been part of it.

The test suite passes under latest Sphinx (2.3.1) on my local dev env, so...it's fine?

Thanks for the push. Making sure RTD can actually build my darn docs this time, then releasing this as 1.6.3. (1.5.x is sufficiently old that I end up with personal-ecosystem circular dependency issues, so that one isn't getting the update for now.)

**Comment by bitprophet** [comment]
Grumble, I was wrong - the unit tests pass under Sphinx 2.3 but not the integration tests! Thanks, Travis-CI.

When I bisect Sphinx versions I actually end up back on 1.7 - even 1.8.1 breaks the integration tests.

However! Something must be at least slightly wonky between those and reality, because OP here says newer Sphinx worked for them, and sure enough our own simple-enough changelog builds fine with 1.8.x.

Also - looking closer I see this is specifically the "util" integration tests, for the util module, which is primarily there to support the other Sphinx-using tools in my personal ecosystem. It's not directly used by Releases internally. So that kinda explains the disparity.

Still tho, it means our CI breaks above Sphinx 1.8, so I'll see if I can fix.

**Comment by bitprophet** [comment]
Made new ticket *gestures at above autolink*
